spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/ewm"
    username: "ewm"
    password: "ewm"
  sql.init.mode: always

logging:
  level:
    org:
      zalando:
        logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, mappings

server:
  port: 0